### PR TITLE
Adding hammock logo to the page.

### PR DESCRIPTION
**Pull request by johnament**

### CODE REVIEW

**Comment by johnament** [comment]
I was unable to run it locally, due to this error:

```java
Caused by: java.lang.IllegalStateException: Unable to resolve config microprofile_blog_root for environment 'base'. Make sure the following property is defined 'microprofile_blog_root = <your config value>' for the 'base' environment
	at org.tomitribe.sabot.ConfigurationExtension.retrieveTypes(ConfigurationExtension.java:119)
	... 37 more

30-Nov-2017 21:44:29.508 SEVERE [localhost-startStop-1] sun.reflect.NativeMethodAccessorImpl.invoke Error deploying web application archive /Users/johnament/src/microprofile-site/target/apache-tomee/webapps/ROOT.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:756)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This setting isn't mentioned in the readme, I'm not sure how to set it.

**Comment by Emily-Jiang** [comment]
To my best knowledge, what you have done should be ok, compared to the PR of adding Oracle logo.

**Comment by lilian-benoit** [comment]
It's not writing on README file. Value of property is microprofile/microprofile-blog. This GIT Repo contents blog entries.

`microprofile_blog_root=microprofile/microprofile-blog`

**Comment by lilian-benoit** [comment]
For information, I create PR #72  for improve README.adoc

**Comment by jroper** [comment]
This will conflict with my PR #73. If this is merged, I'm happy to rebase.

**Pull request merged**
