### PR TITLE
Add Hazelcast Logo and Upgrade build stack

### PR DESCRIPTION
**Pull request by karianna**
Added Hazelcast Logo to supporters.  Upgraded Java build stack and dependencies to latest versions. Upgraded NPM/Node/Bower build stack to latest versions.

### CODE REVIEW

**Comment by karianna** [comment]
Tested locally and site comes up fine.

**Comment by tbookless** [comment]
Hi @karianna could you please update the description of this PR so we have some background on these changes? Then I'll get someone to review it. Thanks.

**Comment by karianna** [comment]
@tbookless Done.

**Comment by tveronezi** [comment]
I will review it and update the site shortly.

**Comment by tveronezi** [comment]
Hi @karianna Is there a missing file in this commit?

screen shot 2017-02-03 at 11 19 41 am

**Comment by karianna** [comment]
Fixed - apologies

Cheers,
Martijn

**Pull request merged**
